#some packages for scRNA-seq analysis
library(Matrix)
library(Matrix.utils)
library(plyr)
library(dplyr)
library(igraph)
library(factoextra)
library(circlize)
library(EpicTools)
require(Hmisc)
library(ggpubr) 
require(openxlsx)
library(ggpubr)
library(ggnewscale)
require(cowplot)
library(data.table)
library(rowr)
library(SingleR)
library(scater)
library(pheatmap)
library(nichenetr)
library(Rmisc)   


#library(arrangements)
library(BiocGenerics)

library(DropletUtils)
library(edgeR)
library(imager)
library(jpeg)
library(matrixStats)
library(NMF)
library(nnls)
library(png)
library(philentropy)
library(purrr)
library(scatterpie)
library(tibble)

library(Matrix)
library(data.table)
library(Seurat)
library(SeuratData)
library(dplyr)
library(gt)
#library(SPOTlight)
library(igraph)
library(RColorBrewer)


library(Seurat)
library(patchwork)
library(ggplot2)
library(rtracklayer)
library(sctransform)
library(clustree)
library(harmony)
library(cowplot)
library(stringr)
library(reticulate)


library(infercnv)
library(tidyverse)
#library(ComplexHeatmap)
library(circlize)
library("RColorBrewer")

#library(SeuratDisk)
library(tidyverse)
library(ggsignif)
library(viridis)
library(reshape2)
library(pBrackets)
library(future)
library(future.apply)
library(MAST)
library(grid)
library(boot)
library(openxlsx)
#library(magick)

library(knitr) # for kable

# For SCTrnsform
library(devtools)
library(glmGamPoi)

library(ggnewscale)
library(ggbeeswarm)
library(ggtext)
library(anndata)
